name: CI

on: [push, pull_request]

jobs:
  run:    
    runs-on: ${{ matrix.operating-system }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.1', '7.2', '7.3', '7.4' ]
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug #optional, setup coverage driver
        tools: phpunit:7.5.20

    - name: Start mysql service
      run: sudo /etc/init.d/mysql start

    - name: Install WP Tests
      run: bash bin/install-wp-tests.sh wordpress_test root root localhost latest
      
    - name: phpunit tests
      run: phpunit